### ISSUE TITLE
Workflows in Markdown?

### ISSUE THREAD

**Issue by bdhhtb** [BioinformaticsSOPs/Workflows#1]
Just a suggestion - since GitHub will then format them prettily for us.

**Comment by scholzmb** [comment]
So, this is a good idea, particularily if we keep this format (one repo for workflows, with "child" repos for each ACTUAL workflow).  If this would  be a universal repo for all, then would need to have BOTH .md versions and .sh versions.

**Comment by scholzmb** [comment]
Committed for both workflows.  Closing
